"""Total policy registry for the deployment environment surface."""

from dataclasses import dataclass
from enum import StrEnum


class Policy(StrEnum):
    EXACT_FINGERPRINT = "exact_fingerprint"
    CAPABILITY_PROBE = "capability_probe"
    VALUE_COMPARISON = "value_comparison"
    EXCLUDED = "excluded"


@dataclass(frozen=True, slots=True)
class SettingPolicy:
    policy: Policy
    secret_bearing: bool = False
    blocks_restore: bool = False


# Literal by design: the env-surface test compares this with its existing scanner, so a
# newly read setting cannot silently inherit a policy.
ENV_SURFACE = frozenset("""
ADMIN_SITE_NAME ALLOWED_HOSTS APICLIENT_REQUIRE_NONCE
API_CLIENT_AUTH_REQUIRED API_CLIENT_ENC_KEY AUDIT_MAC_MASTER_KEY
AUDIT_ATTESTATION_DEPLOYMENT_ID AUDIT_ATTESTATION_ANCHOR_BACKEND AUDIT_ATTESTATION_S3_BUCKET AUDIT_ATTESTATION_S3_PREFIX AUDIT_ATTESTATION_RETENTION_DAYS AUDIT_ATTESTATION_S3_OBJECT_LOCK_MODE AUDIT_ATTESTATION_S3_ENDPOINT_URL AUDIT_ATTESTATION_S3_ACCESS_KEY_ID AUDIT_ATTESTATION_S3_SECRET_ACCESS_KEY AUDIT_ATTESTATION_S3_REGION_NAME AUDIT_ATTESTATION_HTTP_URL AUDIT_ATTESTATION_HTTP_BEARER_TOKEN AUDIT_ATTESTATION_HTTP_TIMEOUT
AUTH_COOKIE_SAMESITE AUTH_COOKIE_SECURE AWS_ACCESS_KEY_ID AWS_S3_ENDPOINT_URL
AWS_S3_PUBLIC_ENDPOINT_URL AWS_S3_REGION_NAME AWS_SECRET_ACCESS_KEY
AWS_STORAGE_BUCKET_NAME AXES_ENABLED AXES_FAILURE_LIMIT BACKUP_AGE_RECIPIENT
BACKUP_ARCHIVE_SIGNING_PRIVATE_KEY BACKUP_ARCHIVE_VERIFY_PUBLIC_KEY
BACKUP_DECISION_SECONDS BACKUP_DOWNLOAD_TTL_SECONDS BACKUP_LEASE_SECONDS
BACKUP_OPS_DIR BACKUP_PRESIGN_DRAIN_SECONDS BACKUP_RECIPIENT_CHALLENGE_TTL_SECONDS
BACKUP_PRODUCER_CAPABILITY_MARKER_PATH BACKUP_PRODUCER_PRIVILEGED_SCRIPTS_DIR
BACKUP_PRODUCER_ENTRYPOINT_PATH BACKUP_PRODUCER_MIGRATIONS_DIR
SPACEWORKS_GRANTS_ONLY SPACEWORKS_GRANT_DATABASE_NAME
SPACEWORKS_HOST_MARKER_PATH SPACEWORKS_HOST_MARKER_WRITE_PATH
SPACEWORKS_RUNTIME_DATABASE_URL
SPACEWORKS_SCHEDULER_MODE SPACEWORKS_SCHEDULER_SERVICES
SPACEWORKS_SCHEDULER_HOST_GATE_COMMAND SPACEWORKS_SCHEDULER_CONTROL_PLANE_DISABLEMENT
TENANT_MIGRATION_GATE_LEASE_SECONDS TENANT_MIGRATION_PRESIGN_DRAIN_SECONDS
TENANT_DUMP_STAGING_DIR TENANT_DUMP_STAGING_MAX_AGE_SECONDS
BEHIND_TRUSTED_PROXY CACHE_URL CELERY_BROKER_URL CELERY_RESULT_BACKEND
CELERY_TASK_ALWAYS_EAGER CONN_MAX_AGE CORS_ALLOWED_ORIGINS CRON_SECRET
CSRF_COOKIE_SECURE CSRF_TRUSTED_ORIGINS DATABASE_URL DATA_EXPORT_DEADLINE_SECONDS
ANONYMOUS_REQUEST_IDEMPOTENCY_KEY_MAX_LENGTH ANONYMOUS_REQUEST_OUTSTANDING_LIMIT
DATA_EXPORT_DOWNLOAD_TTL_SECONDS DATA_EXPORT_PAGE_SIZE DATA_EXPORT_RETENTION_SECONDS
DEBUG DEFAULT_FROM_EMAIL DEVICE_ANDROID_ATTESTATION_VERIFY_TOKEN
DEVICE_ANDROID_ATTESTATION_VERIFY_URL DEVICE_APPLE_ATTESTATION_VERIFY_TOKEN
DEVICE_APPLE_ATTESTATION_VERIFY_URL DEVICE_ATTESTATION_APPS
DEVICE_ATTESTATION_CHALLENGE_TTL_SECONDS DEVICE_ATTESTATION_PROVIDER_TIMEOUT_SECONDS
DISABLE_SERVER_SIDE_CURSORS DOMAIN_CHANGE_COOLDOWN_SECONDS EMAIL_BACKEND EMAIL_HOST
EMAIL_HOST_PASSWORD EMAIL_HOST_USER EMAIL_PORT EMAIL_USE_TLS ENABLE_HTTPS
EVENT_CHECKIN_CLOCK_SKEW_SECONDS EVENT_CHECKIN_ROSTER_LIFETIME_HOURS
EVENT_CHECKIN_ROSTER_MAX EVENT_CHECKIN_SYNC_GRACE_HOURS
EVENT_CHECKIN_WINDOW_AFTER_HOURS EVENT_CHECKIN_WINDOW_BEFORE_HOURS
EVENT_STATION_PIN_PEPPER
EVIDENCE_MAX_BYTES EVIDENCE_URL_TTL_SECONDS EVIDENCE_OBJECT_RETENTION_DAYS
EVIDENCE_OBJECT_EXPIRY_ENABLED EVIDENCE_RETENTION_BATCH_SIZE
GITHUB_API_TOKEN HMAC_CLIENT_ID
HMAC_MAX_CLOCK_SKEW_SECONDS HMAC_PROTECTED_PATH_PREFIXES HMAC_SECRET INFRA_HOSTS
MACHINE_DOC_ALLOWED_EXT MACHINE_DOC_ALLOWED_MIME MACHINE_DOC_MAX_BYTES MANAGED_POSTGRES
MEMBER_CLAIM_CODE_TTL_SECONDS MEMBER_CLAIM_SESSION_TTL_SECONDS OIDC_ATTEMPT_TTL_SECONDS
OIDC_DISCOVERY_CACHE_SECONDS OIDC_HTTP_MAX_BYTES OIDC_HTTP_TIMEOUT_SECONDS
OTP_SMS_DAILY_CAP PII_AWS_KMS_ENDPOINT_URL PII_AWS_KMS_KEY_ID PII_AWS_KMS_REGION
PII_DEK_CACHE_TTL_SECONDS PII_ENCRYPTION_DUAL_READ PII_ENCRYPTION_ENABLED
PII_KEY_BROKER PII_MASTER_KEY PII_MASTER_KEY_PREVIOUS PII_SEARCH_HASH_KEY
PLATFORM_ADMIN_SSO PLATFORM_DOMAIN_SUFFIX PLATFORM_ORIGIN_HOST PLATFORM_STAFF_ORIGINS
PRINT_ALLOWED_MODEL_EXT PRINT_ALLOWED_MODEL_MIME PRINT_UPLOAD_MAX_BYTES
PRINT_URL_TTL_SECONDS PROCUREMENT_RECEIPT_ALLOWED_MIME PROCUREMENT_RECEIPT_MAX_BYTES
PUBLIC_APP_BASE_URL PUBLIC_IMAGE_BASE_URL PUBLIC_IMAGE_BUCKET PUBLIC_IMAGE_MAX_BYTES
PUBLIC_IMAGE_URL_TTL_SECONDS PUSH_TOKEN_HMAC_KEY SECRET_KEY SECURE_HSTS_SECONDS
SECURE_SSL_REDIRECT SESSION_COOKIE_SECURE SOCIAL_APPLE_JWKS_URL
SOCIAL_AUTH_CLOCK_SKEW_SECONDS SOCIAL_AUTH_JWKS_CACHE_SECONDS SOCIAL_AUTH_JWKS_MAX_BYTES
SOCIAL_AUTH_JWKS_TIMEOUT_SECONDS SOCIAL_AUTH_NONCE_TTL_SECONDS SOCIAL_GOOGLE_JWKS_URL
STORAGE_PRESIGN_METHOD STRIPE_CONNECT_REDIRECT_URI TELEGRAM_API_URL TELEGRAM_BOT_TOKEN
TELEGRAM_WEBHOOK_SECRET THROTTLE_ANONYMOUS_REQUEST_EMAIL
THROTTLE_ANONYMOUS_REQUEST_IP_BURST THROTTLE_ANONYMOUS_REQUEST_IP_HOUR
THROTTLE_ARCHIVE_RECIPIENT_VERIFY THROTTLE_BOOKING_SUBMIT THROTTLE_CLIENT_PUBLIC
THROTTLE_EVENT_CALENDAR_FEED_IP THROTTLE_EVENT_CALENDAR_FEED_TOKEN
THROTTLE_EVENT_OFFLINE_ROSTER THROTTLE_EVENT_OFFLINE_SYNC
THROTTLE_EVENT_STATION_PIN_IP THROTTLE_EVENT_STATION_PIN_TOKEN
THROTTLE_EVENT_STATION_REVEAL THROTTLE_EVENT_STATION_SESSION
THROTTLE_CLIENT_STANDARD THROTTLE_CLIENT_TRUSTED THROTTLE_DATA_EXPORT_CREATE
THROTTLE_DEVICE_ATTESTATION_CHALLENGE THROTTLE_DEVICE_LOGIN THROTTLE_DEVICE_LOGIN_USER
THROTTLE_DEVICE_REFRESH THROTTLE_EMAIL_VERIFICATION_CONFIRM
THROTTLE_EMAIL_VERIFICATION_RESEND THROTTLE_EVENT_CHECKIN_RESOLVE
THROTTLE_EVENT_REGISTER THROTTLE_EVENT_REGISTRATION_RETRY THROTTLE_LOGIN
THROTTLE_MEMBERSHIP_REQUEST THROTTLE_MEMBER_CLAIM_ISSUE THROTTLE_MEMBER_CLAIM_REDEEM
THROTTLE_MEMBER_IMAGE_PRESIGN THROTTLE_MEMBER_SIGN_UP
THROTTLE_PRESENCE_START
THROTTLE_MEMBER_VERIFICATION_EMAIL THROTTLE_PASSWORD_RESET_CONFIRM
THROTTLE_PASSWORD_RESET_CONFIRM_EMAIL THROTTLE_PASSWORD_RESET_EMAIL
THROTTLE_PASSWORD_RESET_REQUEST THROTTLE_PHONE_CONFIRM_NUMBER
THROTTLE_PHONE_LOGIN_CONFIRM THROTTLE_PHONE_OTP_NUMBER THROTTLE_PHONE_OTP_REQUEST
THROTTLE_PRINT_REQUEST_SUBMIT THROTTLE_PUBLIC_READ THROTTLE_PUBLIC_REQUEST_SUBMIT
THROTTLE_PUBLIC_STATS THROTTLE_PUBLIC_TOOL_CHECKOUT THROTTLE_PUBLIC_TOOL_RETURN
THROTTLE_PUSH_DEVICE_REGISTRATION THROTTLE_REQUEST_STATUS THROTTLE_REQUEST_SUBMIT
THROTTLE_SOCIAL_LOGIN THROTTLE_SOCIAL_NONCE THROTTLE_TELEGRAM_WEBHOOK
THROTTLE_TENANT_MIGRATION_READ THROTTLE_TENANT_MIGRATION_WRITE
TENANT_MIGRATION_AGE_IDENTITY_FILE TENANT_MIGRATION_AGE_RECIPIENT
TRUSTED_PROXY_COUNT TRUST_X_FORWARDED_PROTO WARRANTY_DOC_ALLOWED_MIME
WARRANTY_DOC_MAX_BYTES
CHECKIN_API_URL CHECKIN_REQUIRED_PURPOSE CHECKIN_TIMEOUT CHECKIN_CACHE_SECONDS
CHECKIN_MAX_RESPONSE_BYTES CHECKIN_MAX_ROWS
THROTTLE_CHECKIN_LOOKUP_IP_BURST THROTTLE_CHECKIN_LOOKUP_IP_HOUR
THROTTLE_CHECKIN_MID THROTTLE_CHECKIN_MID_UPLOAD
BUILD_GIT_DESCRIBE BUILD_GIT_SHA SETUP_MAKERSPACE_NAME SETUP_MAKERSPACE_SLUG
SETUP_MODULE_PROFILE SETUP_SUPERADMIN_EMAIL SETUP_SUPERADMIN_PASSWORD
SETUP_SUPERADMIN_USERNAME SPACEWORKS_OCI_DIGEST TOMBSTONED_APPS
""".split())

# The source-gate lease and presign-drain settings are portable operational timing
# knobs, like the neighbouring backup lease/drain settings. They therefore receive
# the generated EXCLUDED policy rather than participating in restore compatibility.

EXACT = frozenset({
    "SECRET_KEY", "API_CLIENT_ENC_KEY", "PII_MASTER_KEY", "PII_MASTER_KEY_PREVIOUS",
    "PII_SEARCH_HASH_KEY", "HMAC_SECRET", "PUSH_TOKEN_HMAC_KEY", "CRON_SECRET",
    "AUDIT_MAC_MASTER_KEY",
    "AUDIT_ATTESTATION_HTTP_BEARER_TOKEN",
    "AUDIT_ATTESTATION_S3_SECRET_ACCESS_KEY",
    "EVENT_STATION_PIN_PEPPER",
})
CAPABILITY = frozenset({
    "DATABASE_URL", "AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY",
    "AWS_S3_ENDPOINT_URL", "AWS_STORAGE_BUCKET_NAME", "PUBLIC_IMAGE_BUCKET",
    "CACHE_URL", "CELERY_BROKER_URL", "CELERY_RESULT_BACKEND", "EMAIL_HOST",
    "EMAIL_PORT", "EMAIL_HOST_USER", "EMAIL_HOST_PASSWORD",
})
VALUE = frozenset({
    "ALLOWED_HOSTS", "APICLIENT_REQUIRE_NONCE", "API_CLIENT_AUTH_REQUIRED",
    "CORS_ALLOWED_ORIGINS",
    "PLATFORM_DOMAIN_SUFFIX", "PLATFORM_ORIGIN_HOST", "PLATFORM_STAFF_ORIGINS",
    "BEHIND_TRUSTED_PROXY", "ENABLE_HTTPS", "CSRF_TRUSTED_ORIGINS",
    "TRUSTED_PROXY_COUNT", "TRUST_X_FORWARDED_PROTO", "PII_ENCRYPTION_ENABLED",
    "PII_ENCRYPTION_DUAL_READ", "PII_KEY_BROKER", "DEVICE_ATTESTATION_APPS",
    "BACKUP_AGE_RECIPIENT", "TENANT_MIGRATION_AGE_RECIPIENT",
    "BACKUP_ARCHIVE_VERIFY_PUBLIC_KEY",
    "BACKUP_OPS_DIR", "SPACEWORKS_HOST_MARKER_PATH", "MANAGED_POSTGRES",
    # Host-local producer-gate paths: compared like SPACEWORKS_HOST_MARKER_PATH, and
    # non-blocking because a restore target legitimately installs them elsewhere.
    "BACKUP_PRODUCER_CAPABILITY_MARKER_PATH", "BACKUP_PRODUCER_PRIVILEGED_SCRIPTS_DIR",
    "BACKUP_PRODUCER_ENTRYPOINT_PATH", "BACKUP_PRODUCER_MIGRATIONS_DIR",
    "PII_AWS_KMS_ENDPOINT_URL", "PII_AWS_KMS_KEY_ID", "PII_AWS_KMS_REGION",
    "TOMBSTONED_APPS",
    # Which upstream roster admits requesters, and which upstream `purpose`
    # string does it. Both are authorization inputs for the `checked_in`
    # request mode, not operational knobs: a restore that silently pointed a
    # tenant at a different space, or relaxed the purpose, would admit a
    # different set of people than the operator configured. The timeout,
    # cache and size ceilings alongside them are ordinary knobs and stay
    # EXCLUDED.
    "CHECKIN_API_URL", "CHECKIN_REQUIRED_PURPOSE",
})
BLOCKING_VALUE = frozenset({
    "APICLIENT_REQUIRE_NONCE", "API_CLIENT_AUTH_REQUIRED",
    "CHECKIN_API_URL", "CHECKIN_REQUIRED_PURPOSE",
    "PII_ENCRYPTION_ENABLED",
    "PII_ENCRYPTION_DUAL_READ", "PII_KEY_BROKER", "TOMBSTONED_APPS",
    "BACKUP_ARCHIVE_VERIFY_PUBLIC_KEY",
    "PII_AWS_KMS_ENDPOINT_URL", "PII_AWS_KMS_KEY_ID", "PII_AWS_KMS_REGION",
})


POLICIES = {
    name: SettingPolicy(
        Policy.EXACT_FINGERPRINT if name in EXACT else
        Policy.CAPABILITY_PROBE if name in CAPABILITY else
        Policy.VALUE_COMPARISON if name in VALUE else Policy.EXCLUDED,
        secret_bearing=name in EXACT or name in {
            "AWS_SECRET_ACCESS_KEY", "EMAIL_HOST_PASSWORD", "CELERY_BROKER_URL",
            "CELERY_RESULT_BACKEND", "DATABASE_URL", "SPACEWORKS_RUNTIME_DATABASE_URL",
            "BACKUP_ARCHIVE_SIGNING_PRIVATE_KEY",
        },
        blocks_restore=name in EXACT or name in CAPABILITY or name in BLOCKING_VALUE,
    )
    for name in ENV_SURFACE
}


def assert_complete(env_names):
    missing = set(env_names) - set(POLICIES)
    stale = set(POLICIES) - set(env_names)
    if missing or stale:
        raise AssertionError(f"backup setting policies drifted: missing={sorted(missing)}, stale={sorted(stale)}")
