# Generated by Django 6.0.8 on 2026-09-03 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encryption', '0007_tenant_import_fence_operation'),
        ('makerspaces', '0068_public_request_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.TextField()),
                ('mid_exact_hash', models.BinaryField(editable=False, max_length=32, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_identities', to='makerspaces.makerspace')),
                ('mid_hash_generation', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='encryption.searchkeygeneration')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='checkin_identity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('mid_exact_hash__isnull', False), ('mid_hash_generation__isnull', False)), fields=('makerspace', 'mid_hash_generation', 'mid_exact_hash'), name='uniq_checkin_identity_mid_hash')],
            },
        ),
    ]
