# Generated by Django 6.0.8 on 2026-09-03 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
        ('encryption', '0008_checkin_identity_pii_fence'),
        ('makerspaces', '0068_public_request_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='checkinidentity',
            constraint=models.UniqueConstraint(condition=models.Q(('mid_exact_hash__isnull', True)), fields=('makerspace', 'mid'), name='uniq_checkin_identity_mid_plain'),
        ),
    ]
