"""Source-deployment audit identifiers that are snapshots, never target bindings."""

SOURCE_LOCAL_AUDIT_EDGES = frozenset(
    {
        ("event.checkin_roster_downloaded", "lease_id"),
        ("event.checkin_sync_processed", "lease_id"),
        ("event.registration_attended", "operation_id"),
        ("event.registration_attended", "session_id"),
        ("event.station_session_started", "session_id"),
        ("audit.signing_key_rotation_aborted", "rotation_id"),
        ("audit.signing_key_rotation_started", "rotation_id"),
        ("audit.signing_key_rotation_completed", "rotation_id"),
        ("audit.signing_key_rotation_failed", "rotation_id"),
        ("encryption.write_fence_closed", "operation_id"),
        ("encryption.write_fence_opened", "operation_id"),
        ("payment.checkout_created", "subject_id"),
        ("payment.created", "subject_id"),
        ("payment.double_paid_refund_required", "event_id"),
        ("payment.paid_after_terminal", "event_id"),
        ("payment.paid_online", "event_id"),
        ("payments.connect_authorization_revoked", "connect_account_id"),
        ("payments.connect_previous_authorization_revoked", "connect_account_id"),
        ("procurement.moved_to_printing", "result_id"),
        ("qr.rebound", "new_target_id"),
        ("tenant_migration.pairing_approved", "migration_id"),
        ("tenant_migration.pairing_approved", "source_deployment_id"),
        ("tenant_migration.pairing_approved", "target_deployment_id"),
        ("tenant_migration.source_migrated_out", "migration_id"),
        ("tenant_migration.source_migrated_out", "receipt_id"),
        ("tenant_migration.source_migrated_out", "source_deployment_id"),
        ("tenant_migration.source_migrated_out", "target_deployment_id"),
        ("tenant_migration.target_activated", "migration_id"),
        ("tenant_migration.target_activated", "receipt_id"),
        ("tenant_migration.target_activated", "source_deployment_id"),
        ("tenant_migration.target_activated", "target_deployment_id"),
        ("tenant_migration.target_aborted", "migration_id"),
        ("tenant_migration.target_aborted", "receipt_id"),
        ("tenant_migration.target_aborted", "source_deployment_id"),
        ("tenant_migration.target_aborted", "target_deployment_id"),
        ("tenant_migration.source_reopened", "migration_id"),
        ("tenant_migration.source_reopened", "receipt_id"),
        ("tenant_migration.source_reopened", "source_deployment_id"),
        ("tenant_migration.source_reopened", "target_deployment_id"),
        ("tenant_migration.source_gate_closed", "owner_id"),
        ("tenant_migration.source_gate_capture_released", "owner_id"),
        ("tenant_migration.source_gate_recovered", "owner_id"),
        ("tenant_migration.source_gate_reopened", "owner_id"),
        ("tenant_migration.source_gate_recovery_command", "makerspace_id"),
        ("tenant_migration.source_gate_recovery_command", "owner_id"),
        ("tenant_migration.source_gate_migrated_out", "owner_id"),
        ("tenant_migration.source_quiesced", "owner_id"),
        ("tenant_migration.tenant_dump_captured", "gate_owner_id"),
        ("tenant_migration.tenant_dump_derived", "artifact_id"),
        ("tenant_migration.tenant_dump_derived", "capture_id"),
        ("tenant_migration.objects_staged", "job_id"),
        ("tenant_migration.objects_promoted", "job_id"),
        ("tenant_migration.objects_rolled_back", "job_id"),
        ("tenant_migration.export_requested", "export_id"),
        ("tenant_migration.export_read", "export_id"),
        ("data_export.download_url_issued", "export_id"),
        ("data_export.downloaded", "export_id"),
    ("evidence.object_expired", "sweep_run_id"),
        ("tenant_migration.import_created", "import_id"),
        ("tenant_migration.import_read", "import_id"),
        ("tenant_migration.import_run_requested", "import_id"),
        ("tenant_migration.identity_decisions_submitted", "import_id"),
        ("tenant_migration.identity_decisions_read", "import_id"),
        ("tenant_migration.import_completed", "import_id"),
        ("tenant_migration.verification_read", "import_id"),
        # Lane E compound-artifact rows are deployment-operational and never travel.
        ("backup.archive_exclusion_activated", "artifact_id"),
        ("backup.archive_exclusion_activated", "capture_id"),
    }
)
